tasks:
  - command: npm install; echo y | npm install -g @angular/cli

vscode:
  extensions:
    - Angular.ng-template@0.1000.7:0IUEFuDEuIrPL5WlPLev9A==
    - zhuangtongfa.material-theme@3.8.5:g0hzCQNjVo4tGZHXf+w5Mg==