name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Test and Build
      run: npm install; echo n | npm install @angular/cli; npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI;
            
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Test and Build
      run: npm install; echo n | npm install @angular/cli; npm run build
  
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Test and Build
      run: npm install; echo n | npm install @angular/cli; ng lint
