name: CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: npm install; echo n | npm install @angular/cli; npm test -- --no-watch --no-progress --browsers=ChromeHeadless
            
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: npm install; echo n | npm install @angular/cli; npm run build
  
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: npm install; echo n | npm install @angular/cli; npm run lint
